"""create matches

Revision ID: 0002_create_matches
Revises: 0001_create_players
Create Date: 2026-05-27 16:53:25.313451
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002_create_matches"
down_revision: str | Sequence[str] | None = "0001_create_players"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("match_id", sa.Text(), nullable=False),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("queue_id", sa.Integer(), nullable=False),
        sa.Column("game_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("patch", sa.Text(), nullable=True),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("match_id"),
    )
    op.create_index(
        "ix_matches_queue_id_game_start", "matches", ["queue_id", "game_start"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_matches_queue_id_game_start", table_name="matches")
    op.drop_table("matches")
    # ### end Alembic commands ###
