"""create player matches

Revision ID: 0004_create_player_matches
Revises: 0003_create_ranked_entries
Create Date: 2026-05-27 16:54:33.621448
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004_create_player_matches"
down_revision: str | Sequence[str] | None = "0003_create_ranked_entries"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_matches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("player_puuid", sa.Text(), nullable=False),
        sa.Column("match_id", sa.Text(), nullable=False),
        sa.Column("champion_id", sa.Integer(), nullable=False),
        sa.Column("champion_name", sa.Text(), nullable=False),
        sa.Column("team_position", sa.Text(), nullable=True),
        sa.Column("win", sa.Boolean(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("deaths", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("gold_earned", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_minions_killed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("neutral_minions_killed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("vision_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "total_damage_dealt_to_champions", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("summoner_spell_1_id", sa.Integer(), nullable=False),
        sa.Column("summoner_spell_2_id", sa.Integer(), nullable=False),
        sa.Column("item0", sa.Integer(), server_default="0", nullable=False),
        sa.Column("item1", sa.Integer(), server_default="0", nullable=False),
        sa.Column("item2", sa.Integer(), server_default="0", nullable=False),
        sa.Column("item3", sa.Integer(), server_default="0", nullable=False),
        sa.Column("item4", sa.Integer(), server_default="0", nullable=False),
        sa.Column("item5", sa.Integer(), server_default="0", nullable=False),
        sa.Column("item6", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.match_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_puuid"], ["players.puuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_puuid", "match_id", name="uq_player_matches_player_match"),
    )
    op.create_index("ix_player_matches_match_id", "player_matches", ["match_id"], unique=False)
    op.create_index(
        "ix_player_matches_player_champion",
        "player_matches",
        ["player_puuid", "champion_name"],
        unique=False,
    )
    op.create_index(
        "ix_player_matches_player_puuid", "player_matches", ["player_puuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_player_matches_player_puuid", table_name="player_matches")
    op.drop_index("ix_player_matches_player_champion", table_name="player_matches")
    op.drop_index("ix_player_matches_match_id", table_name="player_matches")
    op.drop_table("player_matches")
    # ### end Alembic commands ###
