"""add kda to player matches

Revision ID: 8e46cdaae919
Revises: 0004_create_player_matches
Create Date: 2026-05-27 22:24:30.539907
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '8e46cdaae919'
down_revision: str | Sequence[str] | None = '0004_create_player_matches'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'player_matches',
        sa.Column('kda', sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.execute(
        """
        UPDATE player_matches
        SET kda = ROUND(
            ((kills + assists)::numeric / GREATEST(deaths, 1)::numeric),
            2
        )
        """
    )
    op.alter_column(
        'player_matches',
        'kda',
        existing_type=sa.Numeric(precision=6, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_matches', 'kda')
    # ### end Alembic commands ###
